### ISSUE TITLE
Laravel Query Breaks with GROUP BY restrictive mode

### ISSUE THREAD

**Issue by ftrotter** [CareSet/Zermelo#115]
Look at this error: 

https://lore.ft1.us/api/Zermelo/mostReleasedArt?order[0][card_name]=asc&token=&page=1&length=50&clear_cache=

This is due to line 161 https://github.com/CareSet/Zermelo/blob/master/src/CareSet/Zermelo/Reports/Tabular/ReportGenerator.php

Which apparently generates SQL that results in a "ORDER BY" component that does not have a properly aggregated function. 

To resolve this we can either A: figure out how to get the "selectRaw" command to give the right results.. or (and this is my strong preference) we can not trust Laravel functions to write SQL for us and instead hand craft the SQL that should be generated to create the summary data for the report... I really do not like being dependent on the translation of complex SQL abstraction for the very specific SQL tasks we are trying to accomplish.

In either case, this has to work, not that the latest version of mysql (but not mariadb) ships with the lazy GROUP BY mode off by default... 

-FT

**Comment by kchapple** [comment]
@ftrotter I believe that the "raw" functions in laravel use the underlying PDO directly, but provide bindings to prevent sql injection. I think the issue might be the query itself, I'll investigate.

**Comment by kchapple** [comment]
I think the query you are trying to execute here is the issue. I can execute the raw SQL from the report and get the same error. The crux of the problem is explained in the exception, that some of the fields in your SELECT clause are not encapsulated in the group. For example, when you "SELECT type_line" in your select clause, but don't aggregate it, SQL is undecided which type_line from which result are you are requesting, and that is why the query is throwing an error. You have a couple options. You could leave those fields out of the query, or you could aggregate those fields. There might be some function you could run to get the "first" aggregate value from a group, or something like that.

```
SET SESSION sql_mode='ONLY_FULL_GROUP_BY' 

SELECT GROUP_CONCAT(cardface.name) AS card_name, GROUP_CONCAT(oracle_text), GROUP_CONCAT(type_line), GROUP_CONCAT(mtgset.name,' ',mtgset.released_at
ORDER BY mtgset.released_at ASC SEPARATOR '<br>') AS set_list, COUNT(DISTINCT(mtgset.id)) AS set_count, GROUP_CONCAT(image_uri_art_crop), GROUP_CONCAT(scryfall_web_uri)
FROM lore.cardface
JOIN lore.card ON card.id = cardface.card_id
JOIN lore.mtgset ON mtgset.id = card.mtgset_id
WHERE type_line NOT LIKE '%Basic Land%' AND type_line NOT LIKE '%Token%'
GROUP BY oracle_id, illustration_id HAVING set_count >= 10
ORDER BY MAX(mtgset.released_at) DESC
```

For example, in the result set, for the above query where we use aggregate functions in the select clause, I can see in the 'image_uri_art_crop' column, that the aggregate value contains a bunch of different URLs. Without aggregating those fields, SQL has no way to know which URL you would like to return in the result, which is why the original query is invalid with the ONLY_FULL_GROUP_BY mode enabled. Here is the example data for the image_uri_art_crop column for one row of results from my aggregated query.


`https://img.scryfall.com/cards/art_crop/front/b/b/bb41ff5c-9617-4033-a4fa-99323640b9c3.jpg?1563898896,https://img.scryfall.com/cards/art_crop/front/b/4/b433b9fc-69fc-4a57-a16b-f1afd3033b56.jpg?1562303844,https://img.scryfall.com/cards/art_crop/front/e/d/ed02eba7-f9ef-418d-9c8e-6e7d2bd3869d.jpg?1562855581,https://img.scryfall.com/cards/art_crop/front/2/e/2e3727cf-e4f8-4900-aeee-23ff36109c67.jpg?1562167021,https://img.scryfall.com/cards/art_crop/front/8/a/8a453212-6014-4fe2-8308-8d03f8cd76a4.jpg?1561771524,https://img.scryfall.com/cards/art_crop/front/2/8/2854b2aa-5fa7-41c1-81c9-c2df8f6a7bfa.jpg?1562385575,https://img.scryfall.com/cards/art_crop/front/c/c/ccfa743c-b30a-4576-8205-8f00970d1076.jpg?1562835183,https://img.scryfall.com/cards/art_crop/front/f/7/f7201d43-ae2e-4faa-a508-8555079c3bc7.jpg?1562562029,https://img.scryfall.com/cards/art_crop/front/a/f/af440c35-c549-4532-8c8d-78d312f5f56f.jpg?1562930280,https://img.scryfall.com/cards/art_crop/front/7/e/7e1445d6-ae16-492c-a378-d3aa5746c610.jpg?1562465420
`
