### ISSUE TITLE
Define what "Stable View" means

### ISSUE THREAD

**Issue by tmccormi** [CareSet/Zermelo#63]
What does is a stable view and how is one identified?   per SprintEndTests.md

**Comment by ftrotter** [comment]
I am inclined to say that "yes" we should be using semantic versioning.

And that a "breaking change" should be from the perspective of the report designer. So if the "report file" needs to change structure, then it needs to have a major revision number change. I would like to allow, however, for pretty major changes to the front end views, etc etc... without major revision changes. 

As for "stable view". I would expect that the reporting engine views should themselves be subject to major/minor version numbers, to represent that they are subject to the same basic requirements. 

So a stable view will be anything with a 1.x or higher semantic numbering. 

For the initial release of zermelo, we should be treating the tabular version of the reporting engine as the only thing that we are aiming for 1.0 release for. 

I would like to also use the card reporting just to test that things are generally working with the "one engine multiple view model". That we are pursuing. So I would use it for testing just so that we do not test a single view on what is supposed to be a multiple engine system. However, getting to a 1.0 version of the card reporting system is not itself a priority at this stage. 

Does that work?

**Comment by tmccormi** [comment]
Yes that seems clear and follows industry standards
