### ISSUE TITLE
CSV download extra "<br>", ordering

### ISSUE THREAD

**Issue by rickgithubs** [CareSet/Zermelo#77]
Not sure if this has already been addressed, but it seems that the CSV downloads add a `<br>` to the end of some of the string results. Found when downloading a CSV from a report that field names from a database and their "ordinal position" Also it seems to populate the csv in "reverse" order - from the position 40 -1, when on the screen its 1-40

**Comment by ftrotter** [comment]
Generally, this should be tested by having a test case where a complex csv file is imported into the LOAD DATA command (which can break things, so we need to be careful to have carefully constructed data going in) 

and then have a report which simply reads from the table and make certain that a valid CSV file is being generated when this happens. As artificats like the one that Rick is decribing are found, the "exported dataset for testing" needs to grow to include more of the broken cases, so that we can make sure CSV export is working on all of the strange cases.

A good chance to test for charset problems.

**Comment by ftrotter** [comment]
For now, I am going to close this. I have not been able to replicate a case where a `<br>` is coming out of the CSV downloads, and for now we are not supporting the feature of modifying the CSV download using the datatables filters and sorts. (That may be a 2.0 feature or not support at all, its hard to tell if that is useful and it could be a huge support burden in the tool).

Closing for now.
